{
 "title": "Blackbox exporter Chromedp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Http Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_error",
     "legendFormat": "{{instance}} - {{URL}} - {{StatusCode}}"
    }
   ]
  },
  {
   "title": "Other Error",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "probe_other_error" }
   ]
  },
  {
   "title": "Chrome Console Message",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "probe_chrome_console_message" }
   ]
  },
  {
   "title": "Top High Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg_over_time(probe_http_requests_duration_seconds[5m]))",
     "legendFormat": "{{instance}} - {{URL}}"
    }
   ]
  },
  {
   "title": "Http Total Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Request Total Count" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_request_count) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DOM Content Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_http_dom_content_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Http page load latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_http_page_load_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}